name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'           # publish khi push tag vX.Y.Z
  release:
    types: [published] # hoặc publish khi publish a Release

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install build deps
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Run tests (optional)
        run: |
          pip install -e ".[test]" || true
          pytest -q || true

      - name: Build sdist and wheel
        run: python -m build

      - name: Check dist with twine
        run: twine check dist/*

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*
